Running run.py with a block not yet present on the local node gives an
IndexError.

Failed transactions aren't detected, meaning the failed value AND gas fee are
deducted from the source account.

